var express = require('express');
var router = express.Router();
const Controller = require('../controllers/categoriesController');
router.get('/', Controller.getAllCategories);
router.get('/:id', Controller.getCategory);
router.post('/', Controller.addCategory);
router.delete('/', Controller.deleteAllCategories);
router.delete('/:id', Controller.deleteCategoryById);
router.put('/:id', Controller.updateCategories);
module.exports = router;