var express = require('express');
var router = express.Router();
const Controller = require('../controllers/subCategoriesController');
router.get('/', Controller.getAllSubCategories);
router.get('/:id', Controller.getSubCategory);
router.post('/', Controller.addSubCategory);
router.delete('/', Controller.deleteAllSubCategories);
router.delete('/:id', Controller.deleteSubCategory);
router.put('/:id', Controller.updateSubCategory);
module.exports = router;
